# Generated by Django 4.2.1 on 2023-06-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ingredient',
            field=models.TextField(blank=True, null=True),
        ),
    ]
